import type { Metadata } from "next";
import { Montserrat, Source_Sans_3 } from "next/font/google";
import "./globals.css";
import "./index.css";
import ReduxProvider from "@/lib/ReduxProvider";
import Nav from "./components/Nav";
import LogoutModal from "./components/modals/Logout/LogoutModal";
import HooksComponent from "@/lib/HooksComponent";
import { ThemeProvider } from "@/components/ui/theme-provider";
import Sidebar from "@/app/components/Sidebar";

// const inter = Inter({
//   subsets: ["latin"],
//   weight: ["400", "600", "500", "700", "800"],
//   variable: "--font-inter",
// });

const montserrat = Montserrat({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800"],
  variable: "--font-montserrat"
});

const sourceSansPro = Source_Sans_3({
  subsets: ["latin"],
  weight: ["400", "500", "600"],
  variable: "--font-sourcesanspro"
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {

  return (
    <html lang="en">
      <body className={`${montserrat.variable} ${sourceSansPro.variable}`}>
        <ReduxProvider>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
          // disableTransitionOnChange
          >
            <HooksComponent>
              <Nav />
              <Sidebar />
              <LogoutModal />
              {/* <Sidebar /> */}
              {children}
            </HooksComponent>
          </ThemeProvider>
        </ReduxProvider>
      </body>
    </html>
  );
}
